// Get all products
GET http://localhost:4000/product-api/products
###
// Get Product by ID
GET http://localhost:4000/product-api/products/2
###

// Create a new product
POST http://localhost:4000/product-api/new-product
Content-Type: application/json

{
    "id":9,
    "name":"iPad Pro",
    "brand":"Apple",
    "price":81900
}
###

// Update product details
PUT http://localhost:4000/product-api/product
Content-Type: application/json

{
    "id":2,
    "name":"Galaxy S23 Plus",
    "brand":"Samsung",
    "price":95000
}
###

// Delete a product
DELETE http://localhost:4000/product-api/product/2

